### ISSUE TITLE
Autocorrelations

### ISSUE THREAD

**Issue by mcardenass** [tclements/SeisNoise.jl#99]
Hi Tim, I'm trying to calculate autocorrelations and correlations between components for noise daily records. The script loads the records of all available days of the year and saves the stacked signals in SAC format. However, I observe that the daily autocorrelations do not present any variation between them (the spectrum is identical ). Therefore, I doubt whether the correlations between components are being calculated correctly. I appreciate any feedback about the script I'm using. Attach the Julia script and a day noise record in the three components

[ArchivoComprimido.zip](https://github.com/tclements/SeisNoise.jl/files/8021178/ArchivoComprimido.zip)
![CorrelationsTracesAllcomponents](https://user-images.githubusercontent.com/70914204/152928382-4dcd3eab-0639-4761-93f1-a7dc92685ac2.png)
![SpectraNE](https://user-images.githubusercontent.com/70914204/152928400-b7785689-c1b4-4916-8993-3258b064c009.png)
![SpectraZZ](https://user-images.githubusercontent.com/70914204/152928416-9c3ee8a3-85d5-4293-9451-a37384c6430a.png)
.

**Comment by tclements** [comment]
The mixed-components correlations (ZE, ZN, & NE) look good. The problem here is whitening before auto-correlating the ZZ, NN & EE components. The autocorrelation of a band-limited whitened signal in the Fourier domain is a rectangular PSD (like you show in the bottom plot). The Fourier transform pair of a rectangle in the frequency domain is a sinc function in the time domain, which is what your autocorrelations look like. Whitening is removing all information about the medium of propagation from autocorrelations! I would recommend processing autocorrelations separately from the mixed-component correlations. You could try a less harsh temporal normalization for autocorrelations such as clipping or dividing by the moving mean. Hope that helps!

**Comment by mcardenass** [comment]
You're right, I'll follow your recommendation. Thank you
